
package Win;

import CL.UCN.Domain.FakeStoreSystemImpl;

/**
 *
 * @author eduar
 */
public class Interface extends javax.swing.JFrame {
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        registerButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextUser = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresarButton1.setBackground(new java.awt.Color(204, 0, 204));
        ingresarButton1.setForeground(new java.awt.Color(255, 255, 255));
        ingresarButton1.setText("Ingresar");
        ingresarButton1.setBorderPainted(false);
        ingresarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel2.setText("¿No tienes una cuenta?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        registerButton1.setBackground(new java.awt.Color(51, 51, 51));
        registerButton1.setForeground(new java.awt.Color(0, 0, 255));
        registerButton1.setText("registrarse");
        registerButton1.setBorderPainted(false);
        registerButton1.setContentAreaFilled(false);
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 20));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(103, 0, 187));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 240, -1));

        jTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextUser.setText("Usuario");
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jUser.setBackground(new java.awt.Color(51, 0, 102));
        jUser.setForeground(new java.awt.Color(255, 255, 255));
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, -1));

        jTextPassword.setForeground(new java.awt.Color(255, 255, 255));
        jTextPassword.setText("Contraseña");
        getContentPane().add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jPassword.setBackground(new java.awt.Color(51, 0, 102));
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        RegisterFrame re = new RegisterFrame();
        re.setSystem(fakeS);
        re.setVisible(true);
        
        
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void ingresarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButton1ActionPerformed
        String pass = jPassword.getText();
        if(fakeS.login(jUser.getText(), pass))
        {
            setVisible(false);
        }
        else
        {
            jTextField1.setText("DATOS INCORRECTOS");
        }
    }//GEN-LAST:event_ingresarButton1ActionPerformed
    public void setSystem(FakeStoreSystemImpl sys)
    {
        this.fakeS = sys;
    }
    private FakeStoreSystemImpl fakeS;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jTextPassword;
    private javax.swing.JLabel jTextUser;
    private javax.swing.JTextField jUser;
    private javax.swing.JButton registerButton1;
    // End of variables declaration//GEN-END:variables
}
