/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Win;

import CL.UCN.Domain.FakeStoreSystemImpl;
import CL.UCN.Logic.FakeStoreSystem;

/**
 *
 * @author eduar
 */
public class RegisterFrame extends javax.swing.JFrame {


    public RegisterFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jCompleteName = new javax.swing.JTextField();
        jMail = new javax.swing.JTextField();
        jPhone = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jPassword2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contacto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Completo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre de usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jUserName.setBackground(new java.awt.Color(51, 0, 102));
        jUserName.setForeground(new java.awt.Color(255, 255, 255));
        jUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));

        jCompleteName.setBackground(new java.awt.Color(51, 0, 102));
        jCompleteName.setForeground(new java.awt.Color(255, 255, 255));
        jCompleteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompleteNameActionPerformed(evt);
            }
        });
        getContentPane().add(jCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 130, -1));

        jMail.setBackground(new java.awt.Color(51, 0, 102));
        jMail.setForeground(new java.awt.Color(255, 255, 255));
        jMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailActionPerformed(evt);
            }
        });
        getContentPane().add(jMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, -1));

        jPhone.setBackground(new java.awt.Color(51, 0, 102));
        jPhone.setForeground(new java.awt.Color(255, 255, 255));
        jPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(jPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, -1));

        jPassword1.setBackground(new java.awt.Color(51, 0, 102));
        jPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 130, -1));

        jPassword2.setBackground(new java.awt.Color(51, 0, 102));
        jPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrarse");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 560, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNameActionPerformed
        
    }//GEN-LAST:event_jUserNameActionPerformed

    private void jCompleteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompleteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCompleteNameActionPerformed

    private void jMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailActionPerformed

    private void jPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneActionPerformed

    private void jPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1ActionPerformed

    private void jPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text1 = jPassword1.getText();
        String text2 = jPassword2.getText();
        boolean si = true;
        if(jUserName.getText().equals(""))
        {
            jUserName.setText("no valido");
            si = false;
        }
        if(jCompleteName.getText().equals(""))
        {
            jCompleteName.setText("no valido");
            si = false;
        }
        if(jPhone.getText().equals(""))
        {
            jPhone.setText("no valido");
            si = false;
        }
        if(jMail.getText().equals(""))
        {
            jMail.setText("no valido");
            si = false;
        }
        if(text1.equals(""))
        {
            si = false;
        }
        if(text2.equals(""))
        {
            si = false;
        }
        if(!text1.equals(text2))
        {
            si = false;
        }
        
        if(si==true)
        {
            String pass = jPassword1.getText();
            fakeS.register(jUserName.getText(), jCompleteName.getText(), jMail.getText(), jPhone.getText(), pass);
            setVisible(false);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setSystem(FakeStoreSystemImpl sys)
    {
        this.fakeS = sys;
    }
    private FakeStoreSystemImpl fakeS;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCompleteName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jMail;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jPhone;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables
}
